/* Bento
 *
 * $Id: ParsedParameterList.java,v 1.5 2014/11/01 19:49:40 sthippo Exp $
 *
 * Copyright (c) 2002-2014 by bentodev.org
 *
 * Use of this code in source or compiled form is subject to the
 * Bento Poetic License at http://www.bentodev.org/poetic-license.html
 */

package bento.parser;

import bento.lang.*;

import java.util.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.5 $
 */
public class ParsedParameterList extends ParameterList implements Initializable {
    public ParsedParameterList(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(BentoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        if (children != null) {
            ArrayList<DefParameter> list = new ArrayList<DefParameter>(children.length);
            for (int i = 0; i < children.length; i++) {
                list.add((DefParameter) children[i]);
            }
            setList(list);
        } else {
            setList(new EmptyList<DefParameter>());
        }
    }
    
    public void setDynamic() {
        this.setDynamic(true);
    }
}
