/* Bento
 *
 * $Id: ParsedDefParameter.java,v 1.9 2014/11/01 19:49:41 sthippo Exp $
 *
 * Copyright (c) 2002-2014 by bentodev.org
 *
 * Use of this code in source or compiled form is subject to the
 * Bento Poetic License at http://www.bentodev.org/poetic-license.html
 */

package bento.parser;

import bento.lang.*;

import java.util.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.9 $
 */

public class ParsedDefParameter extends DefParameter implements Initializable {
    public ParsedDefParameter(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(BentoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        Type type = DefaultType.TYPE;
        NameNode nameNode = NameNode.ANY;
        if (children != null && children.length > 0) {
            if (children[0] instanceof Type) {
                nameNode = (NameNode) children[1];
                type = computeType((Type) children[0], nameNode);
            } else {
                nameNode = (NameNode) children[0];
                type = computeType(DefaultType.TYPE, nameNode);
            }
        }
        setType(type);
        setName(nameNode);
    }

    private Type computeType(Type type, NameNode nameNode) {
        List<Dim> dims = nameNode.getDims();
        if (dims == null || dims.size() == 0) {
            return type;
        } else {
            return new ComplexType(type, dims, type.getArguments(null));
        }
    }
}
