/* Bento
 *
 * $Id: ParsedInOperator.java,v 1.1 2009/04/06 14:23:33 sthippo Exp $
 *
 * Copyright (c) 2009 by bentodev.org
 *
 * Use of this code in source or compiled form is subject to the
 * Bento Poetic License at http://www.bentodev.org/poetic-license.html
 */

package bento.parser;

import bento.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.1 $
 */
public class ParsedInOperator extends InOperator {

    public ParsedInOperator(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(BentoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
