/* Bento
 *
 * $Id: ParsedCharLiteral.java,v 1.1 2015/04/20 12:50:41 sthippo Exp $
 *
 * Copyright (c) 2015 by bentodev.org
 *
 * Use of this code in source or compiled form is subject to the
 * Bento Poetic License at http://www.bentodev.org/poetic-license.html
 */

package bento.parser;

import bento.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.1 $
 */
public class ParsedCharLiteral extends PrimitiveValue {
    public ParsedCharLiteral(int id) {
        super("", Character.class);
    }

    public void setValue(String val) {
        // unescape backslashes
        val = val.replace("\\n", "\n");
        val = val.replace("\\r", "\r");
        val = val.replace("\\t", "\t");
        val = val.replace("\\\"", "\"");
        val = val.replace("\\\\", "\\");
        
        setValueAndClass(new Character(val.charAt(0)), Character.TYPE);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(BentoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public String toString() {
        return "'" + getString() + "'";
    }
}
