/* Bento
 *
 * $Id: ParsedStringLiteral.java,v 1.7 2014/04/28 13:18:53 sthippo Exp $
 *
 * Copyright (c) 2002-2014 by bentodev.org
 *
 * Use of this code in source or compiled form is subject to the
 * Bento Poetic License at http://www.bentodev.org/poetic-license.html
 */

package bento.parser;

import bento.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.7 $
 */
public class ParsedStringLiteral extends PrimitiveValue {
    public ParsedStringLiteral(int id) {
        super("", String.class);
    }

    public void setValue(String val, boolean singleQuote) {
        // unescape backslashes
        val = val.replace("\\n", "\n");
        val = val.replace("\\r", "\r");
        val = val.replace("\\t", "\t");
        val = val.replace("\\\"", "\"");
        val = val.replace("\\\\", "\\");
        
        // single-quote strings of length 1 become chars
        if (singleQuote && val.length() == 1) {
            setValueAndClass(new Character(val.charAt(0)), Character.TYPE);
        } else {
            setValueAndClass(val, String.class);
        }
    }

    /** Accept the visitor. **/
    public Object jjtAccept(BentoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public String toString() {
        return '"' + getString() + '"';
    }
}
