/* Bento
 *
 * $Id: ParsedConstruction.java,v 1.4 2014/10/27 13:17:57 sthippo Exp $
 *
 * Copyright (c) 2002-2005 by bentodev.org
 *
 * Use of this code in source or compiled form is subject to the
 * Bento Poetic License at http://www.bentodev.org/poetic-license.html
 */

package bento.parser;

import bento.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.4 $
 */
public class ParsedConstruction extends Instantiation implements Initializable {
    public ParsedConstruction(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(BentoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        setReference(children[0]);
        setTrailingDelimiter(true);
    }
    
    public void setConcurrent() {
        setConcurrent(true);
    }
}
