/* Bento
 *
 * $Id: ParsedWithoutPredicate.java,v 1.5 2012/05/29 13:02:51 sthippo Exp $
 *
 * Copyright (c) 2002-2012 by bentodev.org
 *
 * Use of this code in source or compiled form is subject to the
 * Bento Poetic License at http://www.bentodev.org/poetic-license.html
 */

package bento.parser;

import bento.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.5 $
 */
public class ParsedWithoutPredicate extends WithPredicate implements Initializable {
    public ParsedWithoutPredicate(int id) {
        super(false);
    }

    public void init() {
        setReference(children[0]);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(BentoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
    
    void setElementPresent(boolean check) {
        setElementPresenceCheck(check);
    }
}
