/* Bento
 *
 * $Id: ParsedInsertStatement.java,v 1.2 2006/09/08 16:02:01 sthippo Exp $
 *
 * Copyright (c) 2006 by bentodev.org
 *
 * Use of this code in source or compiled form is subject to the
 * Bento Poetic License at http://www.bentodev.org/poetic-license.html
 */

package bento.parser;

import bento.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.2 $
 */

public class ParsedInsertStatement extends InsertStatement {

	public ParsedInsertStatement(int id) {
        super();
    }


    /** Accept the visitor. **/
    public Object jjtAccept(BentoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
    
    public void setAbove() {
        setInsertionPoint(ABOVE);
    }

    public void setBelow() {
        setInsertionPoint(BELOW);
    }
    
}
