/* Bento
 *
 * $Id: ParsedDefCollectionName.java,v 1.2 2014/01/23 14:46:31 sthippo Exp $
 *
 * Copyright (c) 2002-2014 by bentodev.org
 *
 * Use of this code in source or compiled form is subject to the
 * Bento Poetic License at http://www.bentodev.org/poetic-license.html
 */

package bento.parser;

import bento.lang.*;

import java.util.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.2 $
 */
public class ParsedDefCollectionName extends NameWithDims implements Initializable {
    public ParsedDefCollectionName(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(BentoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        int len = children.length;
        List<Dim> dims;
        List<ParameterList> paramLists;        
        if (len == 0) {
            dims = new EmptyList<Dim>();
            paramLists = null;

        } else if (len == 1) {
            dims = new SingleItemList<Dim>((Dim) children[0]);
            paramLists = null;

        } else {
            dims = new ArrayList<Dim>(len);
            paramLists = new ArrayList<ParameterList>(1);           
            for (int i = 0; i < len; i++) {
                if (children[i] instanceof ParameterList) {
                    paramLists.add((ParameterList) children[i]);
                } else {
                    dims.add((Dim) children[i]);
                }
            }
        }
        setDims(dims);
        setParamLists(paramLists);
    }
}
