/* Bento
 *
 * $Id: ParsedTableElement.java,v 1.6 2013/06/24 13:36:38 sthippo Exp $
 *
 * Copyright (c) 2002-2013 by bentodev.org
 *
 * Use of this code in source or compiled form is subject to the
 * Bento Poetic License at http://www.bentodev.org/poetic-license.html
 */

package bento.parser;

import bento.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.6 $
 */
public class ParsedTableElement extends TableElement implements Initializable {
    public ParsedTableElement(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(BentoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        // one child means this is the default entry, which has no key
        if (children.length == 1) {
            setKey(null);
            setElement(children[0]);
        } else {
            if (children[0] instanceof Name) {
                setKey(new PrimitiveValue(((Name) children[0]).getName()));
            } else if (children[0] instanceof Value) {
                setKey((Value) children[0]);
            } else {
                setDynamicKey((ValueGenerator) children[0]);
            }
            setElement(children[1]);
        }
    }

}
