/* Bento
 *
 * $Id: ParsedSiteStatement.java,v 1.5 2014/02/05 14:06:10 sthippo Exp $
 *
 * Copyright (c) 2002-2014 by bentodev.org
 *
 * Use of this code in source or compiled form is subject to the
 * Bento Poetic License at http://www.bentodev.org/poetic-license.html
 */

package bento.parser;

import bento.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.5 $
 */

public class ParsedSiteStatement extends Site implements Initializable {
    public ParsedSiteStatement(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(BentoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        int n = 0;
        if (children.length > 2) {
            setDomainName(children[0].getName());
            n = 1;
        }
        setName((NameNode) children[n]);
        setType(createType());
        setContents(children[n+1]);
    }
}

