/* Bento
 *
 * $Id: ParsedUnderConstruction.java,v 1.2 2008/06/18 13:36:04 sthippo Exp $
 *
 * Copyright (c) 2008 by bentodev.org
 *
 * Use of this code in source or compiled form is subject to the
 * Bento Poetic License at http://www.bentodev.org/poetic-license.html
 */

package bento.parser;

import bento.lang.UnderStatement;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.2 $
 */
public class ParsedUnderConstruction extends UnderStatement {
    public ParsedUnderConstruction(int id) {
        super();
    }

  
    /** Accept the visitor. **/
    public Object jjtAccept(BentoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
