/* Bento
 *
 * $Id: ParsedDim.java,v 1.6 2014/05/29 13:03:24 sthippo Exp $
 *
 * Copyright (c) 2002-2014 by bentodev.org
 *
 * Use of this code in source or compiled form is subject to the
 * Bento Poetic License at http://www.bentodev.org/poetic-license.html
 */

package bento.parser;

import bento.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.6 $
 */
public class ParsedDim extends Dim implements Initializable {
    public ParsedDim(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(BentoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        if (children != null && children.length > 0) {
            AbstractNode node = children[0];
            if (node instanceof Value) {
                int size = ((Value) node).getInt();
                setSize(size);
            } else {
                log("Unable to set Dim size; dimension is not a value.");
            }
        }
    }

    void setDimType(TYPE dimType) {
        setType(dimType);
    }
}
